/*
============================================================================
版权所有 (C) 2008-2010 易族智汇（北京）科技有限公司，并保留所有权利。
网站地址：http://www.javamall.com.cn

您可以在完全遵守《最终用户授权协议》的基础上，将本软件应用于任何用途（包括商
业用途），而不必支付软件版权授权费用。《最终用户授权协议》可以从我们的网站下载；
如果担心法律风险，您也可以联系我们获得书面版本的授权协议。在未经授权情况下不
允许对程序代码以任何形式任何目的的修改或再发布。
============================================================================
*/
package com.enation.javashop.core.model;



/**
 * Template generated by MyEclipse - Hibernate Tools
 */

public class Template  implements java.io.Serializable {


    // Fields    

     private Integer template_id;
     private String name;
     private String theme;
     private String author;
     private String site;
     private Long create_time;
     private Integer is_active;
     private String version;


    // Constructors

    /** default constructor */
    public Template() {
    }


	public String getAuthor() {
		return author;
	}


	public void setAuthor(String author) {
		this.author = author;
	}


	public Long getCreate_time() {
		return create_time;
	}


	public void setCreate_time(Long create_time) {
		this.create_time = create_time;
	}


	public Integer getIs_active() {
		return is_active;
	}


	public void setIs_active(Integer is_active) {
		this.is_active = is_active;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getSite() {
		return site;
	}


	public void setSite(String site) {
		this.site = site;
	}


	public Integer getTemplate_id() {
		return template_id;
	}


	public void setTemplate_id(Integer template_id) {
		this.template_id = template_id;
	}


	public String getTheme() {
		return theme;
	}


	public void setTheme(String theme) {
		this.theme = theme;
	}


	public String getVersion() {
		return version;
	}


	public void setVersion(String version) {
		this.version = version;
	}

    
  

}