package com.qzgf.application.gpsdata.service;

import java.io.IOException;
import java.util.List;


import com.ibatis.common.logging.Log;
import com.ibatis.common.logging.LogFactory;
import com.qzgf.utils.FileZip;
import com.qzgf.utils.StringParseToXML;



//Generated by MyEclipse

public class GetListDatebyBytesImpl implements GetListDatebyBytes {
	private Log log = LogFactory.getLog(GetListDatebyBytesImpl.class);
	private GpsDataService gpsDataServiceBean;
	/**
	 * 压缩数据传输
	 * @param commandStr
	 * @return
	 */
	public byte[] GetCompress(String commandStr)
	{
		byte[] resultArrary=null;
		List datelist=gpsDataServiceBean.ProCommand(commandStr);
		try {
			resultArrary=FileZip.compressList(datelist);
			log.debug("得到压缩后的数组");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			log.debug("得到压缩后的数组异常");
			e.printStackTrace();
		}
		return resultArrary;
	}

	/**
	 * 将数据转化为byte[]
	 * @param commandStr
	 * @return
	 */
	public byte[] GetListToByte(String commandStr){
		byte[] resultArrary=null;
		List datelist=gpsDataServiceBean.ProCommand(commandStr);
		try {
			resultArrary=FileZip.ListToByte(datelist);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return resultArrary;
	}
	/**
	 * 将数据转化为xml
	 * @param commandStr
	 * @return
	 */
	public String GetListToXml(String commandStr){
		String resultxml="";
		List datelist=gpsDataServiceBean.ProCommand(commandStr);
		if(datelist!=null)
		resultxml=StringParseToXML.parseToXML(datelist);
		return resultxml;
	}
	/**
	 * 将数据转化为list->xml->byte
	 * @param commandStr
	 * @return
	 */
	public byte[] GetListToXmlToByte(String commandStr){
		byte[] resultxml=null;
		String strxml="";
		List datelist=gpsDataServiceBean.ProCommand(commandStr);
		if(datelist!=null)
			strxml=StringParseToXML.parseToXML(datelist);
		try {
			resultxml=FileZip.XmlToByte(strxml);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return resultxml;
	}
	
	/**
	 * 动态sql查询结果集
	 * @param commandStr
	 * @return
	 */
	public String DynamicSqlListXml(String commandStr)
	{
		String resultxml="";
		List datelist=gpsDataServiceBean.DynamicCommand(commandStr);
		if(datelist!=null)
		resultxml=StringParseToXML.parseToXML(datelist);
		return resultxml;	
	}
	
	
	/**
	 * 动态sql查询结果集
	 * @param commandStr
	 * @return
	 */
	public byte[] DynamicSqlListXmlToByte(String commandStr)
	{
		byte[] resultxml=null;
		String strxml="";
		List datelist=gpsDataServiceBean.DynamicCommand(commandStr);
		if(datelist!=null)
			strxml=StringParseToXML.parseToXML(datelist);
		try {
			resultxml=FileZip.XmlToByte(strxml);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return resultxml;
	}
	/**
	 * @return the gpsDataServiceBean
	 */
	public GpsDataService getGpsDataServiceBean() {
		return gpsDataServiceBean;
	}

	/**
	 * @param gpsDataServiceBean the gpsDataServiceBean to set
	 */
	public void setGpsDataServiceBean(GpsDataService gpsDataServiceBean) {
		this.gpsDataServiceBean = gpsDataServiceBean;
	}
}