/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.form.BackForm;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-28-2008
 * 
 * XDoclet definition:
 * @struts.form name="manufacturerForm"
 */
@SuppressWarnings("serial")
public class MenuForm extends ActionForm {
    private String theCode;
    private String theName;
    private String theParentCode;
    private String theUrl;
    private String theRemark;
    private Integer theOrderId;

	/**  
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	   // Property accessors

    public String getTheCode() {
        return this.theCode;
    }
    
    public void setTheCode(String theCode) {
        this.theCode = theCode;
    }

    public String getTheName() {
        return this.theName;
    }
    
    public void setTheName(String theName) {
        this.theName = theName;
    }

    public String getTheParentCode() {
        return this.theParentCode;
    }
    
    public void setTheParentCode(String theParentCode) {
        this.theParentCode = theParentCode;
    }

    public String getTheUrl() {
        return this.theUrl;
    }
    
    public void setTheUrl(String theUrl) {
        this.theUrl = theUrl;
    }

    public String getTheRemark() {
        return this.theRemark;
    }
    
    public void setTheRemark(String theRemark) {
        this.theRemark = theRemark;
    }

    public Integer getTheOrderId() {
        return this.theOrderId;
    }
    
    public void setTheOrderId(Integer theOrderId) {
        this.theOrderId = theOrderId;
    }
}