/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.form.BackForm;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2008
 * 
 * XDoclet definition:
 * @struts.form name="newsForm"
 */
@SuppressWarnings("serial")
public class NewsForm extends ActionForm {
	private String NewsId;
	private String NewsTitle;
	private String NewsContent;
	private String ReleaseMan;
	private String ReleaseTime;
	private String IfCommend;
	private String IfFine;
	private String NewsAuthor;
	private String groupName;
	private String description;
    private String content;
    private String [] newsIds;
	public String[] getNewsIds() {
		return newsIds;
	}

	public void setNewsIds(String[] newsIds) {
		this.newsIds = newsIds;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getNewsId() {
		return NewsId;
	}

	public void setNewsId(String newsId) {
		NewsId = newsId;
	}

	public String getNewsTitle() {
		return NewsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		NewsTitle = newsTitle;
	}

	public String getNewsContent() {
		return NewsContent;
	}

	public void setNewsContent(String newsContent) {
		NewsContent = newsContent;
	}

	public String getReleaseMan() {
		return ReleaseMan;
	}

	public void setReleaseMan(String releaseMan) {
		ReleaseMan = releaseMan;
	}

	public String getReleaseTime() {
		return ReleaseTime;
	}

	public void setReleaseTime(String releaseTime) {
		ReleaseTime = releaseTime;
	}

	public String getIfCommend() {
		return IfCommend;
	}

	public void setIfCommend(String ifCommend) {
		IfCommend = ifCommend;
	}

	public String getIfFine() {
		return IfFine;
	}

	public void setIfFine(String ifFine) {
		IfFine = ifFine;
	}

	public String getNewsAuthor() {
		return NewsAuthor;
	}

	public void setNewsAuthor(String newsAuthor) {
		NewsAuthor = newsAuthor;
	}
}