/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.action.BackAction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.qzgf.NetStore.service.IBulletinService;
import com.qzgf.NetStore.struts.form.BackForm.BulletinForm;


public class BulletinAction extends DispatchAction {
	private IBulletinService bulletinService;

	public IBulletinService getBulletinService() {
		return bulletinService;
	}

	public void setBulletinService(IBulletinService bulletinService) {
		this.bulletinService = bulletinService;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward queryBulletin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String bulletinContent=this.bulletinService.getBulletin();
		System.out.println("abc");
		request.setAttribute("bulletinContent", bulletinContent);
		return mapping.findForward("bulletinManage_Page");
	}
	
	public ActionForward updateBulletin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BulletinForm f=(BulletinForm)form;
		String bulletinContent=f.getBulletinContent(); 
		System.out.println("BulletinContent:"+bulletinContent);
		boolean flag=false;
		String xgResult="";
		if(this.bulletinService.getBulletinNumById()==1){
			flag=this.bulletinService.updateBulletin(bulletinContent);
		}
		else{
			flag=this.bulletinService.addBulletin(bulletinContent);
		}
		if(!flag){
			xgResult="公告修改成功";
		}
		else{
			xgResult="公告修改失败,请重试";
		}
		request.setAttribute("xgResult", xgResult);
		String bulletinContent1=this.bulletinService.getBulletin();
		System.out.println("abc");
		request.setAttribute("bulletinContent", bulletinContent1);
		return mapping.findForward("bulletinManage_Page");
	}
	
	
}