/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.action.BackAction;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.qzgf.NetStore.persistence.Menu;
import com.qzgf.NetStore.service.IMenuService;
import com.qzgf.NetStore.struts.form.BackForm.MenuForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-28-2008
 * 
 * XDoclet definition:
 * @struts.action path="/manufacturer" name="manufacturerForm" input="/form/manufacturer.jsp" parameter="status" scope="request" validate="true"
 */
public class MenuAction extends DispatchAction {
	private IMenuService menuService;

	public IMenuService getMenuService() {
		return menuService;
	}

	public void setMenuService(IMenuService menuService) {
		this.menuService = menuService;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("unchecked")
	public ActionForward queryAllMenus(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		@SuppressWarnings("unused")
		List menuList=this.menuService.queryMenus();
		request.setAttribute("menuList", menuList);
		return mapping.findForward("menuManage_Page");
	}
	
	@SuppressWarnings("unchecked")
	public ActionForward queryMenuById(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		@SuppressWarnings("unused")
		String id=request.getParameter("id");
		Map menuMap=this.menuService.queryMenuById(id);
		request.setAttribute("menuMap", menuMap);
		
		List ParentNameList=this.menuService.queryMenus();
		request.setAttribute("ParentNameList", ParentNameList);	
		
		return mapping.findForward("menuModify_Page");
	}
	
	@SuppressWarnings("unchecked")
	public ActionForward updateMenu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		MenuForm f=(MenuForm)form;
		Menu mfr=new Menu();
		mfr.setTheCode(f.getTheCode());
		mfr.setTheName(f.getTheName());
		mfr.setTheOrderId(f.getTheOrderId());
		mfr.setTheParentCode(f.getTheParentCode());
		mfr.setTheRemark(f.getTheRemark());
		mfr.setTheUrl(f.getTheUrl());
		boolean flag=this.menuService.updateMenu(mfr);
		if(flag){
			String xgResult="修改成功";
			request.setAttribute("xgResult", xgResult);
			List menuList=this.menuService.queryMenus();
			request.setAttribute("menuList", menuList);
			return mapping.findForward("menuManage_Page");
		}
		else{
			String xgResult="修改失败,请重试";
			request.setAttribute("xgResult", xgResult);
			return null;
		}
	}
	
	public ActionForward to_addPage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		List ParentNameList=this.menuService.queryMenus();
		request.setAttribute("ParentNameList", ParentNameList);
		return mapping.findForward("menuAdd_Page");
	}
	
	@SuppressWarnings("unchecked")
	public ActionForward addMenu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		MenuForm f=(MenuForm)form;
		Menu mfr=new Menu();
		mfr.setTheCode(f.getTheCode());
		mfr.setTheName(f.getTheName());
		mfr.setTheOrderId(f.getTheOrderId());
		mfr.setTheParentCode(f.getTheParentCode());
		mfr.setTheRemark(f.getTheRemark());
		mfr.setTheUrl(f.getTheUrl());
		boolean flag=this.menuService.addMenu(mfr);
		if(flag){
			String xgResult="添加成功";
			request.setAttribute("xgResult", xgResult);
			List menuList=this.menuService.queryMenus();
			request.setAttribute("menuList", menuList);
			return mapping.findForward("menuManage_Page");
		}
		else{
			String xgResult="修改失败,请重试";
			request.setAttribute("xgResult", xgResult);
			return null;
		}
	}
	
	@SuppressWarnings("unchecked")
	public ActionForward deleteMenuById(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		@SuppressWarnings("unused")
		String id=request.getParameter("id");
		boolean flag=this.menuService.deleteMenuByID(id);
		if(flag){
			String xgResult="删除成功";
			request.setAttribute("xgResult", xgResult);
			List menuList=this.menuService.queryMenus();
			request.setAttribute("menuList", menuList);
			return mapping.findForward("menuManage_Page");
		}
		else{
			String xgResult="删除失败，请重试";
			request.setAttribute("xgResult", xgResult);
			List menuList=this.menuService.queryMenus();
			return mapping.findForward("menuManage_Page");
	    }
	}
}