/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.action.BackAction;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;


import com.qzgf.NetStore.service.IUnitService;

/** 
 * MyEclipse Struts
 * Creation date: 08-19-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/JspForm/errors.jsp"
 * @struts.action-forward name="success" path="/JspForm/BackfuncModual/Unit.jsp"
 */
public class UnitAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private IUnitService unitService;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("unchecked")
	public ActionForward select(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
        
	
		List unitList=this.unitService.unitList();//取得单位列表 
		request.setAttribute("unitList", unitList);
		return mapping.findForward("success");
	}
	
	
	//添加单位
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String addUnitName=request.getParameter("addUnitName");
		this.unitService.addUnit(addUnitName);
		request.setAttribute("xgResult", "成功添加了单位.");
		return mapping.findForward("addSuccess");
	}
	
	//删除delete
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) 
	{
		String uId=request.getParameter("uId");
		this.unitService.delete(uId);
		return mapping.findForward("delSuccess");
	}
	
	//保存
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String unitId [] =request.getParameterValues("unitId");	
	    String unitName [] =request.getParameterValues("unitName");	
	    if(unitName!=null)
	    {
	    	for(int i=0;i<unitName.length;i++)
	    	{
	    		this.unitService.update(unitId[i], unitName[i]);
	    	}
	    }
	    return mapping.findForward("saveSuccess");
	    
	}
	
	
	
	
	
	
	public IUnitService getUnitService() {
		return unitService;
	}
	public void setUnitService(IUnitService unitService) {
		this.unitService = unitService;
	}
}