/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.action.BackAction;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.qzgf.NetStore.struts.form.BackForm.UploadForm;




/** 
 * MyEclipse Struts
 * Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UploadAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward Link(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
	
	   
		
		
		return mapping.findForward("success");
	}
	@SuppressWarnings("deprecation")
	public ActionForward upd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws FileNotFoundException, IOException {
		
		String sWJM="333";
		UploadForm ptdForm = (UploadForm)form;
		
		FormFile inputfile=ptdForm.getWjm();
		
	    if(inputfile==null){
		    return mapping.findForward("failure");
	   }
   
	    /**//*
         * 建立一个上传文件的输出流如果是linux系统请把"\" 换成 "/"
       */

	   InputStream is=inputfile.getInputStream();
	   String path=request.getRealPath("/files/data");
	   OutputStream os= new FileOutputStream(path+"/"+sWJM);

	   int bytes=0;
	   byte[] buffer = new byte[8192];
	   while((bytes=is.read(buffer,0,8192))!=-1){
	    os.write(buffer,0,bytes);
	   }
	   os.close();
	   is.close();
	   inputfile.destroy();
	   
	   
		return null;
	}
	
	
	
}