/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.action.BackAction;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.qzgf.NetStore.service.ISpecificationService;


/** 
 * MyEclipse Struts
 * Creation date: 08-19-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="specSuccess" path="/JspForm/BackfuncModual/Specification.jsp"
 */
public class SpecificationAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private ISpecificationService specService;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("unchecked")
	public ActionForward select(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List specList=this.specService.specList();//取得品牌列表 
		request.setAttribute("specList", specList);
		return mapping.findForward("specSuccess");
	}
	
	//添加品牌
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String addSpecName=request.getParameter("addSpecName");
		this.specService.addSpec(addSpecName);
		
		request.setAttribute("xgResult", "成功添加了品牌．");
		return mapping.findForward("addSpec");
	}
	
	
	//删除delete
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) 
	{
		String specId=request.getParameter("specId");
		this.specService.deleteSpec(specId);
		return mapping.findForward("delSpec");
	}
	
	//保存
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String specId [] =request.getParameterValues("specId");	
	    String specName [] =request.getParameterValues("specName");	
	    if(specName!=null)
	    {
	    	for(int i=0;i<specName.length;i++)
	    	{
	    		this.specService.updateSpec(specId[i], specName[i]);
	    	}
	    }
	  //  request.setAttribute("xgResult", "已经成功添加了新品牌.");
	    return mapping.findForward("saveSpec");
	}
	
	
	
	
	
	
	
	public ISpecificationService getSpecService() {
		return specService;
	}
	public void setSpecService(ISpecificationService specService) {
		this.specService = specService;
	}
}