/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.action.BackAction;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.qzgf.NetStore.service.ITreatyService;
import com.qzgf.NetStore.struts.form.BackForm.TreatyForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-27-2008
 * 
 * XDoclet definition:
 * @struts.action path="/treaty" name="treatyForm" input="/form/treaty.jsp" parameter="status" scope="request"
 */
public class TreatyAction extends DispatchAction {
	private ITreatyService treatyService;

	public ITreatyService getTreatyService() {
		return treatyService;
	}

	public void setTreatyService(ITreatyService treatyService) {
		this.treatyService = treatyService;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward queryTreaty(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String treatyContent=this.treatyService.getTreaty();
		request.setAttribute("treatyContent", treatyContent);
		return mapping.findForward("treatyManage_Page");
	}
	
	public ActionForward updateTreaty(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TreatyForm f=(TreatyForm)form;
		String treatyContent=f.getTreatyContent();
		boolean flag=false;
		String xgResult="";
		if(this.treatyService.getTreatyNumById()==1){
			flag=this.treatyService.updateTreaty(treatyContent);
		}
		else{
			flag=this.treatyService.addTreaty(treatyContent);
		}
		if(!flag){
			xgResult="条约修改成功";
		}
		else{
			xgResult="条约修改失败,请重试";
		}
		request.setAttribute("xgResult", xgResult);
		String treatyContent1=this.treatyService.getTreaty();
		request.setAttribute("treatyContent", treatyContent1);
		return mapping.findForward("treatyManage_Page");
	}
	
	/**
	 * 查询注册条约用于注册新用户
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward queryTreatyToReg(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		try {
			request.setCharacterEncoding("gbk");
		} catch (UnsupportedEncodingException e1) {
			e1.printStackTrace();
		}
		response.setContentType("text/html;charset=gbk");
		response.setHeader("Cache-Control", "no-cache");
        PrintWriter out=null;
        try {
			out = response.getWriter();
		} catch (IOException e1) {
			e1.printStackTrace();
		}

		String  treatyContent=this.treatyService.getTreaty();
		
		out.print(treatyContent);
		return null;
	}
}