/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.form.BackForm;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2008
 * 
 * XDoclet definition:
 * @struts.form name="orderForm"
 */
public class OrderForm extends ActionForm {
	 
	private static final long serialVersionUID = -3429532395875360390L;
	private String orderId;
	 private String userId;
	 private String allSum;
	 private String sendModeId;
	 private String packModeId;
	 private String noneDealModeId;
	 private String orderStatus;
	 private String downOrderTime;
	 private String receiveUserName;
	 private String receiveUserAddress;
	 private String postCode;
	 private String email;
	 private String phone;
	 private String cellPhone;
	 private String payTypeId;
	 private String ifInvoice;
	 private String invoiceUnit;
	 private String remark;
	 private String sendModeName;
	 private String beginDay;//定单的开始时间用于查询 
	 private String endDay;
	 

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getAllSum() {
		return allSum;
	}

	public void setAllSum(String allSum) {
		this.allSum = allSum;
	}

	public String getSendModeId() {
		return sendModeId;
	}

	public void setSendModeId(String sendModeId) {
		this.sendModeId = sendModeId;
	}

	public String getPackModeId() {
		return packModeId;
	}

	public void setPackModeId(String packModeId) {
		this.packModeId = packModeId;
	}

	public String getNoneDealModeId() {
		return noneDealModeId;
	}

	public void setNoneDealModeId(String noneDealModeId) {
		this.noneDealModeId = noneDealModeId;
	}

	public String getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public String getDownOrderTime() {
		return downOrderTime;
	}

	public void setDownOrderTime(String downOrderTime) {
		this.downOrderTime = downOrderTime;
	}

	public String getReceiveUserName() {
		return receiveUserName;
	}

	public void setReceiveUserName(String receiveUserName) {
		this.receiveUserName = receiveUserName;
	}

	public String getReceiveUserAddress() {
		return receiveUserAddress;
	}

	public void setReceiveUserAddress(String receiveUserAddress) {
		this.receiveUserAddress = receiveUserAddress;
	}

	public String getPostCode() {
		return postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCellPhone() {
		return cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	public String getPayTypeId() {
		return payTypeId;
	}

	public void setPayTypeId(String payTypeId) {
		this.payTypeId = payTypeId;
	}

	public String getIfInvoice() {
		return ifInvoice;
	}

	public void setIfInvoice(String ifInvoice) {
		this.ifInvoice = ifInvoice;
	}

	public String getInvoiceUnit() {
		return invoiceUnit;
	}

	public void setInvoiceUnit(String invoiceUnit) {
		this.invoiceUnit = invoiceUnit;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getSendModeName() {
		return sendModeName;
	}

	public void setSendModeName(String sendModeName) {
		this.sendModeName = sendModeName;
	}

	public String getBeginDay() {
		return beginDay;
	}

	public void setBeginDay(String beginDay) {
		this.beginDay = beginDay;
	}

	public String getEndDay() {
		return endDay;
	}

	public void setEndDay(String endDay) {
		this.endDay = endDay;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	

}