/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.form.BackForm;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-12-2008
 * 
 * XDoclet definition:
 * @struts.form name="roleValueForm"
 */
public class RoleValueForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** menuCode property */
	private String[] menuCode;

	/** remark property */
	private String[] remark;

	/** funIsShow property */
	private String[]  funIsShow;
	/** powerValue property */
	private String[] powerValue;

	/** roleId property */
	private String[] roleId;
	
	private String[] checkData;

	/**
	 * @return the menuCode
	 */
	public String[] getMenuCode() {
		return menuCode;
	}

	/**
	 * @param menuCode the menuCode to set
	 */
	public void setMenuCode(String[] menuCode) {
		this.menuCode = menuCode;
	}

	/**
	 * @return the remark
	 */
	public String[] getRemark() {
		return remark;
	}

	/**
	 * @param remark the remark to set
	 */
	public void setRemark(String[] remark) {
		this.remark = remark;
	}

	/**
	 * @return the checkData
	 */
	public String[] getCheckData() {
		return checkData;
	}

	/**
	 * @param checkData the checkData to set
	 */
	public void setCheckData(String[] checkData) {
		this.checkData = checkData;
	}

	/**
	 * @return the funIsShow
	 */
	public String[] getFunIsShow() {
		return funIsShow;
	}

	/**
	 * @param funIsShow the funIsShow to set
	 */
	public void setFunIsShow(String[] funIsShow) {
		this.funIsShow = funIsShow;
	}

	/**
	 * @return the powerValue
	 */
	public String[] getPowerValue() {
		return powerValue;
	}

	/**
	 * @param powerValue the powerValue to set
	 */
	public void setPowerValue(String[] powerValue) {
		this.powerValue = powerValue;
	}

	/**
	 * @return the roleId
	 */
	public String[] getRoleId() {
		return roleId;
	}

	/**
	 * @param roleId the roleId to set
	 */
	public void setRoleId(String[] roleId) {
		this.roleId = roleId;
	}

	
}