/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.action.FrontAction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.qzgf.NetStore.service.IOrderService;

public class NetpayAction extends Action {
   

	private IOrderService orderService;

	public IOrderService getOrderService() {
		return orderService;
	}

	public void setOrderService(IOrderService orderService) {
		this.orderService = orderService;
	}

	
	
	@SuppressWarnings("deprecation")
	public static chinapay.SecureLink getKeyInstance(String MerId,HttpServletRequest request){
		chinapay.PrivateKey key=new chinapay.PrivateKey();
        chinapay.SecureLink t;
        boolean flag;
        flag=key.buildKey(MerId, 0, request.getRealPath("/key/MerPrK.key"));
        if(flag==false){
        	System.out.println("build key error!");
        	return null;
        }
        else{
        	System.out.println("成功加载");
        }
		t=new chinapay.SecureLink(key);
		return t;
	}
	
	public ActionForward test(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		return mapping.findForward("TransGet");
	}
	
	/**
	 * 网银返回信息
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	@SuppressWarnings("deprecation")
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String TransDate = null;
		String MerId = null;
		String OrdId = null;
		String TransType = null;
		String TransAmt = null;
		String CuryId = null;
		String ChkValue = null;
		String OrderStatus = null;
		String GateId = null;
		TransDate = request.getParameter("transdate");
		MerId = request.getParameter("merid");
		OrdId = request.getParameter("orderno");
		TransType = request.getParameter("transtype");
		TransAmt = request.getParameter("amount");
		CuryId = request.getParameter("currencycode");
		OrderStatus = request.getParameter("status");
		
		ChkValue = request.getParameter("checkvalue");
		chinapay.PrivateKey key = new chinapay.PrivateKey();
		chinapay.SecureLink t;
		t = new chinapay.SecureLink(key);
		boolean flag;
		boolean flag1;
		String resultMsg = "";
		flag = key.buildKey("999999999999999", 0, request.getRealPath("/key/PgPubk.key"));
		if (flag == false) {
			System.out.println("文件加载出错");
			resultMsg = "build key error!";
			return null;
		}
		flag1 = t.verifyTransResponse(MerId, OrdId, TransAmt, CuryId,
				TransDate, TransType, OrderStatus, ChkValue);
		if (flag1 == false) {
			resultMsg = "支付失败,请重新付款!";
			System.out.println(resultMsg);
			request.setAttribute("resultMsg", resultMsg);
		} else {
			boolean flag2=this.orderService.updateOrderStatus(OrdId);
			if(flag2){
				request.setAttribute("resultMsg", "支付成功,欢迎再次购买!");
			}
			else{
				request.setAttribute("resultMsg", "支付成功,但订单后台状态修改失败,请联系客服!");
			}
		}
		//return null;
		return mapping.findForward("getChinapayRet_Page");
	}
	
}