/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.qzgf.NetStore.struts.action.FrontAction;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.qzgf.NetStore.pub.Page;
import com.qzgf.NetStore.service.INewsService;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2008
 * 
 * XDoclet definition:
 * @struts.action path="/news" name="newsForm" input="/form/news.jsp" parameter="status" scope="request" validate="true"
 */
public class NewsDisplayAction extends DispatchAction {
	private INewsService newsService;
 
	public INewsService getNewsService() {
		return newsService;
	}

	public void setNewsService(INewsService newsService) {
		this.newsService = newsService;
	}

	/** 
	 * 查询所有的新闻
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("unchecked")
	public ActionForward queryAllNews(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//NewsForm f = (NewsForm) form;
		@SuppressWarnings("unused")
		String page =request.getParameter("page");
		if ("".equals(page) || page==null)	{
			page =request.getParameter("targetPage");
		}
		
		if ("".equals(page) || page==null)	{
			page="1";
		}
		//判断一下输入的页值是不是大于总的页数
		String totalPages= request.getParameter("totalPages");
		if  (!"".equals(totalPages) && totalPages!=null)
			if ((Integer.parseInt(page))>(Integer.parseInt(totalPages)))//输入的页数不能超过总页数
				page=totalPages;
	         //判断一下输入的页值是不是大于总的页数	
			request.setAttribute("targetPage", page);
			request.setAttribute("page", page);
		Page ppage = this.newsService.queryAllNews(Integer.parseInt(page));
		request.setAttribute("ppage",ppage);
		return mapping.findForward("listNews_Page");

	}
	
	/**
	 * 查询某一条新闻用于显示给客户看的
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public ActionForward queryNewsById(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//NewsForm f = (NewsForm) form;
		@SuppressWarnings("unused")
		String id=request.getParameter("id");
		Map newsMap=new HashMap();
        newsMap=this.newsService.queryNewsById(id); 
        request.setAttribute("newsMap", newsMap);
		return mapping.findForward("newsDisplay_Page");

	}
}